foreach(required PREVIEW PROFILE STATE OUTPUT_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "missing ${required}")
    endif()
endforeach()
file(READ "${PROFILE}" current)
foreach(kind IN ITEMS old_schema old_keys missing_plan)
    set(content "${current}")
    if(kind STREQUAL "old_schema")
        string(REPLACE "g1_arm_static_site_v2" "g1_arm_static_site_v1" content "${content}")
        set(expected "legacy confirmation flags are not migrated automatically")
    elseif(kind STREQUAL "old_keys")
        string(REPLACE "loss_response_plan_reviewed" "loss_recovery_confirmed" content "${content}")
        string(REPLACE "normal_release_plan_reviewed" "normal_release_confirmed" content "${content}")
        set(expected "loss_response_plan_reviewed")
    else()
        string(REPLACE "loss_response_plan_reviewed=true\n" "" content "${content}")
        set(expected "loss_response_plan_reviewed")
    endif()
    file(WRITE "${OUTPUT_DIR}/${kind}.conf" "${content}")
    execute_process(COMMAND "${PREVIEW}" --profile "${OUTPUT_DIR}/${kind}.conf"
        --state "${STATE}" --output "${OUTPUT_DIR}/${kind}.jsonl"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
        message(FATAL_ERROR "${kind} was not explicitly rejected: ${output}${error}")
    endif()
endforeach()
